Rosconsole android backend
Intermodalics/ros_android pull request #53
Opened 2018-12-04 15:30 UTC by ivanpauno

Added an android log backend to rosconsole. Based on the existing glog backend.
It is building ok. I haven't yet tried it at run time as I don't have an example app working.

2018-12-05 13:45 UTC, jubeira commented
Thanks for submitting this @ivanpauno.
So the patch is basically this file right? https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rosconsole/src/rosconsole/impl/rosconsole_glog.cpp. Perhaps I'd download and copy the file instead of adding it to a patch directly, but that's not a strong opinion. @meyerj thoughts?

2018-12-05 20:08 UTC, meyerj requested changes

2018-12-05 20:08 UTC, meyerj commented on patches/rosconsole.patch
> ++  set(ROSCONSOLE_BACKEND "android")
Please respect the cache variable and do not select `android` unconditionally. Could be a good default option, but we might want to use `glog` instead.

Currently the `ROSCONSOLE_BACKEND` is set to `print` in [build_cpp.sh:112](https://github.com/Intermodalics/ros_android/blob/d66b958cc304145ef8183b0fed06cad002905bc1/build_cpp.sh#L112). I suggest to remove that cmake option and use the default defined here instead.

2018-12-05 20:08 UTC, meyerj commented on patches/rosconsole.patch
> ++    index++;
```
/opt/ros_android/catkin_ws/src/ros_comm/rosconsole/src/rosconsole/impl/rosconsole_android.cpp:80:5: warning: variable 'index' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]                        
    index++;                                                                                                                                                                                                                           
    ^                                                                                                                                                                                                                                  
/opt/ros_android/catkin_ws/src/ros_comm/rosconsole/src/rosconsole/impl/rosconsole_android.cpp:74:40: note: incremented here                                                                                                            
  for(size_t index = 0; index < count; index++)                                                                                                                                                                                        
                                       ^                                                                                                                                                                                               
1 warning generated.                                                                         
```

2018-12-06 13:40 UTC, ivanpauno commented on patches/rosconsole.patch
> ++  set(ROSCONSOLE_BACKEND "android")
Changed. I let them in the following priority order: log4cxx, android, glog, print.
I also deleted that cmake option from build_cpp

2018-12-06 13:48 UTC, ivanpauno commented on patches/rosconsole.patch
> ++    index++;
That was copy pasted from glog backend. It was later corrected here https://github.com/ros/rosconsole/pull/15
I added it to the patch, it seems that glog backend is not well tested.

2018-12-10 09:52 UTC, meyerj approved these changes

2018-12-10 13:15 UTC, merged

2018-12-12 00:17 UTC, meyerj reviewed
My original review was only based on code review.

I finally tested this PR today and did not see any ROS messages in the `adb logcat` output. Does it need to enabled? I was running a node from the adb shell.

2018-12-12 00:17 UTC, meyerj commented on patches/rosconsole.patch
> ++    // ignore debug
?

2018-12-12 00:17 UTC, meyerj commented on patches/rosconsole.patch
> ++  if(level == ::ros::console::levels::Info)
use a `switch` statement?

2018-12-12 00:17 UTC, meyerj commented on patches/rosconsole.patch
> ++std::vector<std::pair<std::string, levels::Level> > rosconsole_android_log_levels;
Is this vector protected against concurrent access?

I do not see any mutex protection in [ros::console::get_loggers()](https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rosconsole/src/rosconsole/rosconsole.cpp#L696) or [ros::console::set_logger_level()](https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rosconsole/src/rosconsole/rosconsole.cpp#L701).

2018-12-12 00:17 UTC, meyerj commented on patches/rosconsole.patch
> ++      return (void*)index;
Is this returned `handle` stable? Probably yes, because elements are never removed after they have been added to the vector.

2018-12-12 13:35 UTC, meyerj commented
Update: After I recompiled everything with `-DROSCONSOLE_BACKEND=android` it did work and I see the log output in `adb logcat`.

The `tag` is apparently limited to 94 characters and after that the file name and line number is missing in the output. Not sure whether it is a limitation of the Android logging framework or only the `logcat` tool. So I suggest to omit the file name and line number and only output the logger name in the tag. Like that, we can also avoid the `std::stringstream`:
```patch
-  std::stringstream ss;
-  ss << name << ": in file:" << file << ":" << line;
- __android_log_print(android_log_level, ss.str().c_str(), "%s", str);
+ __android_log_print(android_log_level, name, "%s", str);
```