Fix for toolchain flags.
Intermodalics/ros_android pull request #87
Opened 2019-01-10 17:12 UTC by jubeira

See https://github.com/Intermodalics/ros_android/pull/79#discussion_r246809440.

2019-01-10 18:10 UTC, meyerj requested changes
Seems to work. At least the `-g` flag disappeared again from compiler command lines.

For the `RelWithDebInfo` build I am not sure about the exact order or whether the remainder of the file is required at all. I think it can be completely removed. If not, `CMAKE_*_FLAGS_RELWITHDEBINFO` is cached below, after copying the values of `CMAKE_*_FLAGS_RELEASE`. So in theory it should contain `ANDROID_COMPILER_FLAGS_RELEASE` then and the last three lines will add `ANDROID_COMPILER_FLAGS_RELWITHDEBINFO` again.

Line 20 is not necessary because `ANDROID_COMPILER_FLAGS_RELWITHDEBINFO` copied from `ANDROID_COMPILER_FLAGS_RELEASE` has already been converted to a space-separated string in the included toolchain file.

2019-01-11 15:28 UTC, jubeira commented
I just submitted the changes; PTAL @meyerj

2019-01-11 21:19 UTC, meyerj approved these changes

2019-01-11 21:26 UTC, merged

2019-01-11 21:42 UTC, meyerj commented
The last three lines could have been removed, too, but it also does not matter:
```
if(ANDROID_TOOLCHAIN STREQUAL clang)
  list(APPEND ANDROID_COMPILER_FLAGS_RELWITHDEBINFO -fno-limit-debug-info)
endif()
```

`ANDROID_COMPILER_FLAGS_RELWITHDEBINFO` is not used directly afaik. At the moment `CMAKE_*_FLAGS_RELWITHDEBINFO` are the same as `CMAKE_*_FLAGS_RELEASE` with `-g` preprended, and only those will be forwarded to the compiler. So `-fno-limit-debug-info` would not be set for `RelWithDebInfo`. Not sure whether it would be required.